### ISSUE TITLE
Arcade Insertion failing on multiple repos

### ISSUE THREAD

**Issue by livarcocc** [dotnet/arcade#3380]
Arcade insertion is failing on a few different repos on a InstallDotnetCore task.

For MSbuild and CLI, it is failing before of InstallDotnetCore task:
MSBuild: https://dev.azure.com/dnceng/public/_build/results?buildId=277368&view=logs
CLI: https://dev.azure.com/dnceng/public/_build/results?buildId=277352&view=logs&jobId=07f6ed88-c070-54c0-e916-7efdadbbaf90

For dotnet/sdk, it fails because it can't find vswhere
dotnet/sdk: https://dev.azure.com/dnceng/public/_build/results?buildId=277348&view=logs

**Comment by riarenas** [comment]
@JohnTortugo Is this related to https://github.com/dotnet/arcade/pull/3377?

**Comment by jcagme** [comment]
Looks like it is, and if this is the case should be fixed once https://dnceng.visualstudio.com/internal/_build/results?buildId=278091 is merged and the version is propagated. Still @JohnTortugo can you confirm please?

**Comment by JohnTortugo** [comment]
Yes, it's what @jcagme said. This should be fixed once a new version is propagated.

**Comment by livarcocc** [comment]
This is still failing with this at dotnet/sdk:

error NU1101: Unable to find package vswhere. No packages exist with this id in source(s): dotnet-core

For the CLI, for some reason, there hasn't been an Arcade update there.

**Comment by JohnTortugo** [comment]
That's weird, I'm not aware of changes around that package. I'll take a look

**Comment by JohnTortugo** [comment]
Added a fix to the Maestro's branch/PR

**Comment by markwilkie** [comment]
Can this been confirmed fixed @JohnTortugo ?

**Comment by JohnTortugo** [comment]
Yes, the Maestro PRs for updating Arcade are now working. At least for the above mentioned repos and a few others I can confirm that. For instance [SDK](https://github.com/dotnet/sdk/pull/3474), [CLI](https://github.com/dotnet/sdk/pull/3474) and [MSBuild ](https://github.com/microsoft/msbuild/pull/4558 )Maestro PR.

@livarcocc please re-open the issue or ping me if you think this is still an ongoing problem.
