### ISSUE TITLE
Make VSTest the default test runner

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#4539]
https://github.com/microsoft/vstest now pushes to the ".NET Core Tooling Dev" [BAR channel](https://maestro-prod.westus2.cloudapp.azure.com/548/https:%2F%2Fgithub.com%2Fmicrosoft%2Fvstest/latest/graph) and pushes their packages to the corresponding [dotnet-tools feed](https://dnceng.visualstudio.com/public/_packaging?_a=package&feed=dotnet-tools%40Local&package=Microsoft.NET.Test.Sdk&protocolType=NuGet&version=16.5.0-preview-20191211-02).

All dependency flow related prerequisites are now fulfilled so that we should be able to add VSTest as a supported (and probably default) test runner to Arcade. I recently added support for VSTest in dotnet/runtime and it was fairly simple: https://github.com/dotnet/runtime/blob/f58a38cb9963f88925647317e03b78db7fc9a759/eng/testing/xunit/vstest.targets#L3-L30.

VSTest supports code coverage measurement as well which was asked for several times in the past.

cc @markwilkie @tmat @singhsarab @ManishJayaswal

**Comment by tmat** [comment]
Did you mean https://github.com/microsoft/vstest?

**Comment by ViktorHofer** [comment]
Fixed, thanks.

**Comment by tmat** [comment]
I think we still can't make it default for repos that test on .NET Framework due to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002535

**Comment by markwilkie** [comment]
I just poked the devdiv bug

**Comment by tmat** [comment]
Not being default should block making it available for repos though, if they decide to opt-in.

**Comment by tmat** [comment]
I believe the Arcade SDK test infra makes it easy to plug in another test runner.

**Comment by markwilkie** [comment]
Seems there's not much more to do here.  Closing.

**Comment by ViktorHofer** [comment]
> I think we still can't make it default for repos that test on .NET Framework due to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002535

This is now fixed and available in the SDK that Arcade consumes. Hence reopening. I believe we should make VSTest the default (and by that protect it in CI) and remove xunit.console support (as it is deprecated).

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
