### ISSUE TITLE
Add publishing for vs 17.3 channel

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8788]
- [X] This issue is blocking 
Repos are already attempting to publish to this channel: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5989395&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1&l=65
- [ ] This issue is causing unreasonable pain

Publishing configuration for the 17.3 channel should be added to https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/PublishingConstants.cs. It should be configured with the same feeds as previous 17.x channels

**Comment by dominoFire** [comment]
I am seeing the same error when I try to add a NuGet build to "VS 17.3" channel.

Build ID: https://dev.azure.com/devdiv/devdiv/_build/results?buildId=5998110 

```
PS C:\src\arcade\eng\common> darc authenticate
PS C:\src\arcade\eng\common> darc add-build-to-channel --id 131604 --channel "VS 17.3" --source-branch main --publishing-infra-version 3 --publish-installers-and-checksums
Build 131604 will be assigned to target channel(s) once this build finishes publishing assets: https://dev.azure.com/devdiv/devdiv/_build/results?buildId=5998110
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
The promotion build finished but the build isn't associated with at least one of the target channels. This is an error scenario.
Details are available in the following build: https://dev.azure.com/devdiv/devdiv/_build/results?buildId=5998110 For any questions, contact @dnceng```

**Comment by riarenas** [comment]
Yes. Until this issue is closed every repository that tries to publish to the "vs 17.3" will fail.

**Comment by alexperovich** [comment]
This configuration has been updated. Things should work now.

**Comment by AR-May** [comment]
hmm, I rerun the pipeline and I still getting the same error:
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=6000376&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1&l=65

**Comment by dominoFire** [comment]
I can run the command successfully, but I can not see any PRs associated with my build. Usually, I see PRs to dotnet/sdk repo, but now, there's none:

PS C:\src\arcade\eng\common> darc add-build-to-channel --id 131604 --channel "VS 17.3" --source-branch main --publishing-infra-version 3 --publish-installers-and-checksums
Build 131604 will be assigned to target channel(s) once this build finishes publishing assets: https://dev.azure.com/devdiv/devdiv/_build/results?buildId=6002016
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Build '131604' was successfully added to the target channel(s).
Assigning build '131604' to the following channel(s):
        VS 17.3

Repository:    https://github.com/nuget/nuget.client
Branch:        dev
Commit:        5b0ee2562df6cf2c66cc9905a8a65f2b09ea5473
Build Number:  6.3.0.10
Date Produced: 5/4/2022 14:42
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5985668
AzDO Build Id: 5985668
BAR Build Id:  131604
Released:      False
Channels:
PS C:\src\arcade\eng\common> darc get-build --id 131604
Repository:    https://github.com/nuget/nuget.client
Branch:        dev
Commit:        5b0ee2562df6cf2c66cc9905a8a65f2b09ea5473
Build Number:  6.3.0.10
Date Produced: 5/4/2022 14:42
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5985668
AzDO Build Id: 5985668
BAR Build Id:  131604
Released:      False
Channels:
- VS 17.3

**Comment by riarenas** [comment]
There are no subscriptions in the sdk repo for the vs 17.3 channel. Please work with the dotnet/sdk team if you believe these are subscriptions that should be enabled at this point in time, or if Nuget should be adding their builds to a different channel. 

```
darc get-subscriptions --source-repo nuget.client --target-repo sdk --channel "vs 17.3"
No subscriptions found matching the specified criteria.
```

**Comment by riarenas** [comment]
Builds can now publish to the vs 17.3 channel. This is resolved.
